import type { Country, Station } from "~/types/radio";

const CONTINENT_MAP: Record<string, string> = {
  DZ: "Africa",
  AO: "Africa",
  BJ: "Africa",
  BW: "Africa",
  BF: "Africa",
  BI: "Africa",
  CM: "Africa",
  CV: "Africa",
  CF: "Africa",
  TD: "Africa",
  KM: "Africa",
  CD: "Africa",
  CG: "Africa",
  CI: "Africa",
  DJ: "Africa",
  EG: "Africa",
  GQ: "Africa",
  ER: "Africa",
  SZ: "Africa",
  ET: "Africa",
  GA: "Africa",
  GM: "Africa",
  GH: "Africa",
  GN: "Africa",
  GW: "Africa",
  KE: "Africa",
  LS: "Africa",
  LR: "Africa",
  LY: "Africa",
  MG: "Africa",
  MW: "Africa",
  ML: "Africa",
  MR: "Africa",
  MU: "Africa",
  YT: "Africa",
  MA: "Africa",
  MZ: "Africa",
  NA: "Africa",
  NE: "Africa",
  NG: "Africa",
  RE: "Africa",
  RW: "Africa",
  SH: "Africa",
  ST: "Africa",
  SN: "Africa",
  SC: "Africa",
  SL: "Africa",
  SO: "Africa",
  ZA: "Africa",
  SS: "Africa",
  SD: "Africa",
  TZ: "Africa",
  TG: "Africa",
  TN: "Africa",
  UG: "Africa",
  EH: "Africa",
  ZM: "Africa",
  ZW: "Africa",
  AE: "Asia",
  AF: "Asia",
  AM: "Asia",
  AZ: "Asia",
  BH: "Asia",
  BD: "Asia",
  BT: "Asia",
  BN: "Asia",
  KH: "Asia",
  CN: "Asia",
  GE: "Asia",
  HK: "Asia",
  IN: "Asia",
  ID: "Asia",
  IR: "Asia",
  IQ: "Asia",
  IL: "Asia",
  JP: "Asia",
  JO: "Asia",
  KZ: "Asia",
  KW: "Asia",
  KG: "Asia",
  LA: "Asia",
  LB: "Asia",
  MO: "Asia",
  MY: "Asia",
  MV: "Asia",
  MN: "Asia",
  MM: "Asia",
  NP: "Asia",
  KP: "Asia",
  OM: "Asia",
  PK: "Asia",
  PH: "Asia",
  QA: "Asia",
  SA: "Asia",
  SG: "Asia",
  KR: "Asia",
  LK: "Asia",
  SY: "Asia",
  TW: "Asia",
  TJ: "Asia",
  TH: "Asia",
  TL: "Asia",
  TR: "Asia",
  TM: "Asia",
  UZ: "Asia",
  VN: "Asia",
  YE: "Asia",
  AL: "Europe",
  AD: "Europe",
  AT: "Europe",
  BY: "Europe",
  BE: "Europe",
  BA: "Europe",
  BG: "Europe",
  HR: "Europe",
  CY: "Europe",
  CZ: "Europe",
  DK: "Europe",
  EE: "Europe",
  FO: "Europe",
  FI: "Europe",
  FR: "Europe",
  DE: "Europe",
  GI: "Europe",
  GR: "Europe",
  VA: "Europe",
  HU: "Europe",
  IS: "Europe",
  IE: "Europe",
  IM: "Europe",
  IT: "Europe",
  XK: "Europe",
  LV: "Europe",
  LI: "Europe",
  LT: "Europe",
  LU: "Europe",
  MT: "Europe",
  MD: "Europe",
  MC: "Europe",
  ME: "Europe",
  NL: "Europe",
  MK: "Europe",
  NO: "Europe",
  PL: "Europe",
  PT: "Europe",
  RO: "Europe",
  RU: "Europe",
  SM: "Europe",
  RS: "Europe",
  SK: "Europe",
  SI: "Europe",
  ES: "Europe",
  SE: "Europe",
  CH: "Europe",
  UA: "Europe",
  GB: "Europe",
  AX: "Europe",
  AG: "North America",
  BS: "North America",
  BB: "North America",
  BZ: "North America",
  BM: "North America",
  CA: "North America",
  KY: "North America",
  CR: "North America",
  CU: "North America",
  DM: "North America",
  DO: "North America",
  SV: "North America",
  GL: "North America",
  GD: "North America",
  GP: "North America",
  GT: "North America",
  HT: "North America",
  HN: "North America",
  JM: "North America",
  MQ: "North America",
  MX: "North America",
  NI: "North America",
  PA: "North America",
  PR: "North America",
  KN: "North America",
  LC: "North America",
  PM: "North America",
  VC: "North America",
  TT: "North America",
  TC: "North America",
  US: "North America",
  VI: "North America",
  AS: "Australia",
  AU: "Australia",
  CK: "Australia",
  FJ: "Australia",
  PF: "Australia",
  GU: "Australia",
  KI: "Australia",
  MH: "Australia",
  FM: "Australia",
  NR: "Australia",
  NC: "Australia",
  NZ: "Australia",
  NU: "Australia",
  NF: "Australia",
  MP: "Australia",
  PW: "Australia",
  PG: "Australia",
  WS: "Australia",
  SB: "Australia",
  TK: "Australia",
  TO: "Australia",
  TV: "Australia",
  VU: "Australia",
  WF: "Australia",
  AR: "South America",
  BO: "South America",
  BR: "South America",
  CL: "South America",
  CO: "South America",
  EC: "South America",
  FK: "South America",
  GF: "South America",
  GY: "South America",
  PY: "South America",
  PE: "South America",
  SR: "South America",
  UY: "South America",
  VE: "South America",
};

export function getContinent(iso2?: string): string {
  if (!iso2) return "Other";
  return CONTINENT_MAP[iso2.toUpperCase()] || "Other";
}

export function dedupeStations(stations: Station[]): Station[] {
  const seen = new Set<string>();
  const unique: Station[] = [];
  for (const station of stations) {
    const key = createStationKey(station);
    if (!seen.has(key)) {
      seen.add(key);
      unique.push(station);
    }
  }
  return unique;
}

function createStationKey(station: Station): string {
  const fingerprint = getStreamFingerprint(station);
  return `${station.uuid}::${fingerprint}`;
}

function getStreamFingerprint(station: Station): string {
  const source = station.streamUrl || station.url || "";
  if (!source) return "no-stream";
  try {
    const url = new URL(source);
    return `${url.origin}${url.pathname}`.toLowerCase();
  } catch {
    return source;
  }
}
