import { Link } from "@remix-run/react";
import { useEffect, useState } from "react";
import { BRAND } from "~/constants/brand";
import { useSecretTrail } from "~/state/secretTrail";

export const meta = () => [{ title: `A room between hours · ${BRAND.name}` }, { name: "description", content: "A quiet ending for people who followed the hour." }, { name: "robots", content: "noindex, nofollow" }];

export default function SecretRoom() {
  const hydrated = useSecretTrail((state) => state.hydrated); const hydrate = useSecretTrail((state) => state.hydrate);
  const stage = useSecretTrail((state) => state.stage); const answer = useSecretTrail((state) => state.appAnswer); const answerApp = useSecretTrail((state) => state.answerApp);
  const [shareStatus, setShareStatus] = useState(""); useEffect(() => hydrate(), [hydrate]);
  if (!hydrated) return <main className="ew-secret-room" aria-busy="true" />;
  if (stage !== "room") return <main className="ew-secret-room ew-secret-room-empty"><p className="rp-eyebrow text-foil">The room between hours</p><h1 className="ew-coverline">This mark is easy to miss.</h1><p className="rp-lede">A signal in Theater knows the way.</p><Link to="/listen" className="ew-secret-home" prefetch="intent" viewTransition>Return to Theater →</Link></main>;
  async function shareElsewhere() { const url = window.location.origin; const text = "Some nights, choosing is too much. Let the world take the first turn."; try { if (navigator.share) await navigator.share({ title: BRAND.name, text, url }); else if (navigator.clipboard) { await navigator.clipboard.writeText(url); setShareStatus("Home link copied. Leave the ending a surprise."); } } catch { /* dismissing share is an ordinary choice */ } }
  return <main className="ew-secret-room"><div className="ew-secret-room-inner"><p className="rp-eyebrow text-foil">The room between hours</p><div className="ew-secret-story"><p>You came here because a little mark looked out of place.</p><p>Maybe choosing one more thing felt like too much tonight.</p><h1>I didn’t know where to go either.</h1></div><img className="ew-secret-traveler" src="/secret-traveler.webp" alt="A small illustrated traveler with a scarf holding out a hand" width="360" height="540" /><div className="ew-secret-ask"><p>So we made somewhere to land.</p><h2>Do you want us to make Elsewhere an app?</h2>{answer ? <><p className="ew-secret-answer">{answer === "yes" ? "Your yes stays on this device. The radio will always be free. If we make the app, this is where you could save the second chair." : "That's all right. The radio is still yours to wander through."}</p>{answer === "yes" ? <div className="ew-secret-coffee"><img src="/secret-coffee-table.webp" alt="An illustrated traveler at a small table with an empty chair and a second coffee" width="520" height="434" /><div><p className="rp-eyebrow text-foil">One more chair</p><p>Not a paywall. Just a quiet way to buy the next round when there is something real to help make.</p><span className="ew-secret-coming" aria-label="Support opening soon">Support opening soon</span><button type="button" onClick={() => void shareElsewhere()}>Give someone a place to land →</button></div></div> : null}{shareStatus ? <p role="status">{shareStatus}</p> : null}</> : <div className="ew-secret-choice"><button type="button" onClick={() => answerApp("yes")}>Yes, I'd like that</button><button type="button" onClick={() => answerApp("not-now")}>Not tonight</button></div>}<Link to="/" className="ew-secret-home" prefetch="intent" viewTransition>Back to the air →</Link></div></div></main>;
}
